### PR TITLE
adding bringToFront and updating puppeteer version to 3.0.1

### PR DESCRIPTION
**Pull request by Cmdv**
Is it worth moving things over to psc-package? just had a bit of a nightmare with  nix home-manager because of pulp and looks like the tests aren't running in the CI too now 😂

### CODE REVIEW

**Comment by justinwoo** [comment]
Nice. Yeah, I have to try to fix the CI setup at some point. Remind me if I haven't looked at this again in a couple of days, it'd be nice to make this work. And yeah, I think using Psc-Package would be nice and simple for this project

**Comment by Cmdv** [comment]
cool I'll make the conversion and I'll have a shot at the CI, you have a library set up I can do a bit of copy pasta?

**Comment by justinwoo** [comment]
I think all of my libraries are likely broken in the same way right now. I think it might even be that in the workflow you just want to specify the specific purescript version instead of trying to get it with that hacky means in https://github.com/justinwoo/purescript-toppokki/blob/7247906f8126d70b17d4b3493bd051ddf76eb1c1/.github/workflows/ci.yml#L18

**Comment by Cmdv** [comment]
haha yeah cool, I looked at that line and wondered what was happening there. some strong `sed` usage 💪 

I'll play with it, it's one of them days for me 😹

**Comment by Cmdv** [comment]
@justinwoo fixed the tests and getting the tar but was too lazy to convert it to use psc-package!! 

Is it best to do a minor release on its own or as part of a PR?

ps just noticed your avatar 😂

**Comment by Cmdv** [comment]
ignore question about minor release, I'll just merge this in and do a minor release. Think is should be cool

**Pull request merged**
