### PR TITLE
Add user agent control

### PR DESCRIPTION
**Pull request by alextes**
Does a tiny bit of cleaning up too.

### CODE REVIEW

**Comment by justinwoo** [comment]
:+1: let me know when we should merge thsi

**Comment by justinwoo** [comment]
oops

**Comment by alextes** [comment]
@justinwoo ready now 👍 . 

I'll try and be more careful with the pushing before double-checking the commits next time.

**Comment by justinwoo** [comment]
Np, going to test the new CI setup now on #14

**Pull request merged**
