### PR TITLE
add evaluateOnNewDocument

### PR DESCRIPTION
**Pull request by Cmdv**
This is in reference to #15 
Looked at doing tests but wasn't sure what I could actually do?

### CODE REVIEW

**Comment by justinwoo** [comment]
as long as you call it and do some kind of hello world it will be good enough

**Comment by Cmdv** [comment]
cool I'll add one

**Comment by Cmdv** [comment]
tests added and it all works 🎉

**Comment by justinwoo** [comment]
cool, thanks

**Comment by justinwoo** [comment]
published as 2.1.0: https://pursuit.purescript.org/packages/purescript-toppokki/2.1.0

**Pull request merged**
