### PR TITLE
Extend LaunchOptions to accept more values

### PR DESCRIPTION
**Pull request by Cmdv**
more launch values 😸

### CODE REVIEW

**Comment by justinwoo** [comment]
nice

**Comment by justinwoo** [comment]
Feel free to push another minor release if you need it

**Comment by Cmdv** [comment]
ah yeah I do but unsure how to do it

**Comment by justinwoo** [comment]
should be able to just take master, run `pulp version minor`, and `pulp publish`

**Comment by justinwoo** [comment]
i added you as contrib so probably you need to make this repo the git remote origin first

**Comment by Cmdv** [comment]
ah cool easy, thought you meant something else.. I'll do that now 👍 

thanks for adding me, probably going to be adding a load more stuff due to using this at work 😄

**Pull request merged**
